
package cn.wuwenlun.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestHa", targetNamespace = "http://ws.wuwenlun.cn/", wsdlLocation = "http://127.0.0.1:12345/weather?wsdl")
public class TestHa
    extends Service
{

    private final static URL TESTHA_WSDL_LOCATION;
    private final static WebServiceException TESTHA_EXCEPTION;
    private final static QName TESTHA_QNAME = new QName("http://ws.wuwenlun.cn/", "TestHa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12345/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTHA_WSDL_LOCATION = url;
        TESTHA_EXCEPTION = e;
    }

    public TestHa() {
        super(__getWsdlLocation(), TESTHA_QNAME);
    }

    public TestHa(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTHA_QNAME, features);
    }

    public TestHa(URL wsdlLocation) {
        super(wsdlLocation, TESTHA_QNAME);
    }

    public TestHa(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTHA_QNAME, features);
    }

    public TestHa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestHa(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherImplTest
     */
    @WebEndpoint(name = "WeatherPortImp")
    public WeatherImplTest getWeatherPortImp() {
        return super.getPort(new QName("http://ws.wuwenlun.cn/", "WeatherPortImp"), WeatherImplTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherImplTest
     */
    @WebEndpoint(name = "WeatherPortImp")
    public WeatherImplTest getWeatherPortImp(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wuwenlun.cn/", "WeatherPortImp"), WeatherImplTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTHA_EXCEPTION!= null) {
            throw TESTHA_EXCEPTION;
        }
        return TESTHA_WSDL_LOCATION;
    }

}
